version: "3.9"
services:
  app:
    # image: node:16
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/miyagi
      - PORT=8000
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: miyagi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
